export default {
  async contactCoach(context, payload) {
    const newRequest = {
      userEmail: payload.email,
      message: payload.message,
    };

    const resp = await fetch(
      `https://coach-finder-de40b-default-rtdb.asia-southeast1.firebasedatabase.app/requests/${payload.coachId}.json`,
      { method: "POST", body: JSON.stringify(newRequest) }
    );

    const respData = resp.json();

    if (!resp.ok) {
      throw new Error(respData.message || "Failed to send.");
    }

    // respData received from firebase has uinique id store under the key name
    // We don't want to send coach id to db rather keep it local as we already have dynamic id generated by firebase
    this.contactCoach.id = respData.name;
    this.contactCoach.coachId = payload.coachId;
    context.commit("addRequest", newRequest);
  },

  async loadAllMessagesAction(context) {
    const coachId = context.rootGetters.userId;
    const resp = await fetch(
      `https://coach-finder-de40b-default-rtdb.asia-southeast1.firebasedatabase.app/requests/${coachId}.json`
    );

    const respData = await resp.json();
    console.dir(respData);

    if (!resp.ok) {
      throw new Error(respData.message || "Failed to fetch.");
    }

    const requests = [];
    for (let key in respData) {
      const reqData = {
        id: key,
        coachId: coachId,
        userEmail: respData[key].userEmail,
        message: respData[key].message,
      };
      requests.push(reqData);
    }

    context.commit("setRequestsMutation", requests);
  },
};
